# Site settings
title: Michelle Heatherly
title_separator: "|"
subtitle: "Cats, Coffee, and Code"
email: michelleheatherly218@outlook.com
description: Full-Stack Software Engineer
github_username: michelleheatherly
url: "https://michelleheatherly.github.io"
baseurl: "/blog"
repository: "michelleheatherly/blog"
teaser: "/assets/images/placeholder-pic.jpg"
logo: "/assets/images/transparent-cat.png"
masthead_title: " "
breadcrumbs: true
words_per_minute: 200
minimal_mistakes_skin: neon-custom
minimal_mistakes_skin_light: contrast-custom
search: false

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-polyglot

readme_index:
  enabled: false

# Polyglot
languages: ["en", "de"]
default_lang: "en"
exclude_from_localization:
  - "assets"
  - "favicon.ico"
  - "README.md"
parallel_localization: true
lang_from_path: true
lang_vars:
  - "locale"
locale: "en"

author:
  name: "Michelle Heatherly"
  avatar: "/assets/images/bio.png"
  bio: "Full-Stack Software Engineer"
  email: "michelleheatherly218@outlook.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://michelle-heatherly.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rachael-michelle-heatherly/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/michelleheatherly"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/michelleheatherly"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rachael-michelle-heatherly/"

defaults:
  # EN posts
  - scope:
      path: "_posts/en"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      lang: en
      locale: en
      date_format: "%B %d, %Y"
  # DE posts
  - scope:
      path: "_posts/de"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      lang: de
      locale: de
      date_format: "%d.%m.%Y"
  # Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
